### ISSUE TITLE
`palette` ignored in plotting

### ISSUE THREAD

**Issue by flying-sheep** [theislab/scvelo#150]
When I do `scv.pl.scatter(..., color='some_categorical_obs_column', palette=['#FE57A1', '#BADA55', '#1A5E25'])` I just see the default palette colors.

By the way: when I specify an list of RGB/RGBA tuples (or a n_colors×3 array) as palette instead, I get a warning. That should also be supported.

Scvelo version 0.1.25

**Comment by flying-sheep** [comment]
It’s weird, it seems like you set `<column>_colors` *after* plotting?

Because I was to lazy to bring a debugger, to get a stack trace I replaced `adata.uns` with a custom class that raises an error when `'num_cells_color'` is being set:

```pytb
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-9-5c469b2fd620> in <module>
     10 for letter, kw, ax in zip(ascii_lowercase, kws, axes.flatten()):
     11     print(kw)
---> 12     scv.pl.scatter(adata, **kw, color='num_cells', palette='viridis', frameon=True, title="", ax=ax, show=False)
     13     ax.set_xticks([])
     14     ax.set_yticks([])

/usr/lib/python3.8/site-packages/scvelo/plotting/scatter.py in scatter(adata, x, y, basis, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_fontsize, legend_fontweight, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, show_density, show_assignments, show_linear_fit, show_polyfit, rug, add_outline, outline_width, outline_color, n_convolve, smooth, rescale_color, dpi, frameon, zorder, ncols, wspace, hspace, show, save, ax, **kwargs)
    249                 c = interpret_colorkey(adata, basis, color, perc, use_raw)  # phase portrait: color=basis, layer=color
    250             else:
--> 251                 c = interpret_colorkey(adata, color, layer, perc, use_raw)  # embedding, gene trend etc.
    252 
    253             if c is not None and not isinstance(c, str) and not isinstance(c[0], str):

/usr/lib/python3.8/site-packages/scvelo/plotting/utils.py in interpret_colorkey(adata, c, layer, perc, use_raw)
    299     if c is None: c = default_color(adata)
    300     if issparse(c): c = make_dense(c).flatten()
--> 301     if is_categorical(adata, c): c = get_colors(adata, c)
    302     elif isinstance(c, str):
    303         if c in adata.obs.keys():  # color by observation key

/usr/lib/python3.8/site-packages/scvelo/plotting/utils.py in get_colors(adata, c)
    290             palette = default_palette(None)
    291             palette = adjust_palette(palette, length=len(adata.obs[c].cat.categories))
--> 292             adata.uns[c + '_colors'] = palette[:len(adata.obs[c].cat.categories)].by_key()['color']
    293         cluster_ix = adata.obs[c].cat.codes.values
    294         return np.array([adata.uns[c + '_colors'][cluster_ix[i]]

<ipython-input-7-c0ca56052a7e> in __setitem__(self, key, value)
      2     def __setitem__(self, key, value):
      3         if key == 'num_cells_colors':
----> 4             raise Exception('gotcha')
      5         super().__setitem__(key, value)
      6 adata._uns = DBG(adata.uns)

Exception: gotcha
```

**Comment by flying-sheep** [comment]
re: your question about setting `uns[f'{column}_color']` at all:

I assume the idea is that subsequent plots that *don’t* specify a color are less typing, but I feel that `color='magma'` or `palette='Set'` is little enough typing.

**Comment by VolkerBergen** [comment]
Was just an indentation mistake.. Would you have a look whether it is now resolved for you as well?

**Comment by flying-sheep** [comment]
You mean “just” in the sense of “easy to fix” I assume :wink: 

Apple had a security issue because of one: [goto fail](https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/)

**Comment by flying-sheep** [comment]
Nope, not resolved. Here’s a complete, reproducible example:

```py
import pandas as pd
from anndata import AnnData
import scvelo as scv

import matplotlib.pyplot as plt
import seaborn as sns


iris = sns.load_dataset('iris')
iris = AnnData(iris.iloc[:, :4], pd.DataFrame(dict(species=pd.Categorical(iris['species']))))

scv.pl.scatter(iris, x="sepal_length", y="sepal_width", color='species', palette='viridis', frameon=True, title="")
```
Output:
> `0.1.26.dev17+g36760f3`
> ![grafik](https://user-images.githubusercontent.com/291575/74028642-2491ed80-49ab-11ea-8a64-3bf1012ca593.png)

(If you do `git rev-list --count v0.1.25..36760f3` you can see that there’s 17 commits to master since 36760f3, so your fix is in)

**Comment by VolkerBergen** [comment]
@flying-sheep resolved?

**Comment by flying-sheep** [comment]
You can make the code above into a test: If the plot uses vega colors instead of viridis, it should fail.

**Comment by DmitryVel** [comment]
Hi,

Thanks for the great package. I am trying to use a custom palette in scvelo 0.1.25 and it does not work. Passing a list of colors to palette argument of velocity_embedding and scatter functions gets ignored. Passing a dict causes a warning saying it has to be a list of color names or a string pointing to a colormap.

Was this issue fixed in the current version of scvelo?
Thanks

**Comment by VolkerBergen** [comment]
The fix is not yet released and would need to be installed from source
`pip install git+https://github.com/theislab/scvelo`.
