### ISSUE TITLE
Concatene and merge - smooth layer integration

### ISSUE THREAD

**Issue by Jachimdejonghe** [theislab/scvelo#179]
Hi, 
I hope you are well and thanks a lot for developing scVelo, its super nice and easy to use.
My problem is that I have many samples, for which I have UMIcount matrices (adata) and velocyto loom files (ldata). 

What I have done so far is merge all adata with ldata and then concatenate. The issue is I can't use join ='outer' because the spliced and unspliced layers disapear and some weird variables appear:
>>adata_1 = scv.utils.merge(adata1,ldata1)
>>adata_2 = scv.utils.merge(adata2,ldata2)
>>adata_3 = scv.utils.merge(adata3,ldata3)

>>a65 = adata_1.concatenate(adata_2,adata_3,join = 'outer')
>>a65
layers concatenation is not yet available for 'outer' intersection and will be ignored.
AnnData object with n_obs × n_vars = 3060 × 26624 
    obs: 'batch', 'initial_size', 'initial_size_spliced', 'initial_size_unspliced'
    var: 'Accession-0', 'Chromosome-0', 'End-0', 'Start-0', 'Strand-0', 'Accession-1', 'Chromosome-1', 'End-1', 'Start-1', 'Strand-1', 'Accession-2', 'Chromosome-2', 'End-2', 'Start-2', 'Strand-2'

>> a65 = adata_1.concatenate(adata_2,adata_3)
>>a65
AnnData object with n_obs × n_vars = 3060 × 18616 
    obs: 'batch', 'initial_size', 'initial_size_spliced', 'initial_size_unspliced'
    var: 'Accession', 'Chromosome-0', 'End', 'Start', 'Strand', 'Chromosome-1', 'Chromosome-2'
    layers: 'matrix', 'ambiguous', 'spliced', 'unspliced'

The problem is, if I do not use join = "outer", I lose way too many genes and can't properly follow-up with the analysis. i.e if a gene is detected in adata1 and not the two others, it will be lost. 

Would you know what the best solution to my problem is. At the moment I am thinking of proceeding to merging everything in Seurat and then exporting as a loom, but also run into problems there.

Thanks a lot for your help!
Jo

**Comment by VolkerBergen** [comment]
Thanks. Generally, I would not recommend to use the outer join in this context, because non-shared variables will be filled with zeros/Nans. I'd try to investigate first, why the gene names do not match, maybe that is due to some upper/lower case? 
You can do so by copying code snippets from the [merge module](https://github.com/theislab/scvelo/blob/9eee3e1db97fb290b8747b44285a41b19c9a6a6e/scvelo/read_load.py#L103), e.g. `common_vars = pd.unique(adata.var_names.intersection(ldata.var_names))`.

**Comment by Jachimdejonghe** [comment]
Hi Volker, Thanks!

No these samples are ran on the same pipeline and the names are given by sc.queries.biomart_annotations as my matrices are with ensemble annotation. What happens is that for memory and storage reasons, count matrices only include detected genes (I think all the commonly used tools do that). So if sample 1 has some genes that are not detected in sample 2 (and the other way around), then they will be excluded from concatenation, even if this biologically makes sense, as different samples can have different clusters.
 I think in this case it is actually more dangerous to not fill the non-common genes with 0's. I also think this is probably a common problem for people that multiplex a lot of samples in an analysis (e.g. perturb ate cells with different conditions).  It would be great to add an option in concatenate that allows for both layer and count matrix "outer" concatenation. Because for now, my strategy has losses both for matrix counts but also for spliced and unspliced counts, and I really think this actually removes a lot of the heterogeneity present in my sample.

I will try out your suggestions, but am quite new to python so I am not sure if I can get very far!

Thank you very much again for everything.
Best wishes,
Jo

**Comment by VolkerBergen** [comment]
Thanks for the detailed explanation. I agree, we need outer join then. Will make an issue/PR for `anndata`.

**Comment by Jachimdejonghe** [comment]
Thank you Volker!

**Comment by VolkerBergen** [comment]
It should be solved now. Would appreciate if you could give me a short update whether it works for you.

**Comment by Jachimdejonghe** [comment]
Hi Volker, I still encounter the issues after updating to scanpy-1.5.1 scvelo-0.2.1 anndata-0.7.4  when I concatenate with join = "outer". Without join = "outer", it works as before but removes the genes that are not found in all concatenated objects.
