### ISSUE TITLE
Discrepancy between fluxes and latent time

### ISSUE THREAD

**Issue by ogandril** [theislab/scvelo#208]
I was not expecting this: when I color-code cells for latent time and overlay the velocity fluxes, those fluxes do not originate from the earlier latent time point.

Am I missing something? In the paper, both earlier time point and fluxes origin do coincide.

![Figure_4](https://user-images.githubusercontent.com/18306816/83735529-cc18e700-a650-11ea-8a5c-a9b15d27d0f0.png)

**Comment by VolkerBergen** [comment]
That's strange indeed. Are you running on the latest version 0.2.1?

Could you quickly show what you obtain with
```
scv.tl.terminal_states(adata)
scv.pl.scatter(adata, c=['root_cells', 'end_points'])
```

**Comment by ogandril** [comment]
> Le 4 juin 2020 à 11:39, Volker Bergen <notifications@github.com> a écrit :
> 
> 
> That's strange indeed. Are you running on the latest version 0.2.1?
> 
Nope:
>>> scv.logging.print_version()
Running scvelo 0.2.0 (python 3.7.6) on 2020-06-04 12:29.
WARNING: There is a newer scvelo version available on PyPI:
 Your version: 		 0.2.0 
 Latest version: 	 0.2.1

Shall I upgrade?
> Could you quickly show what you obtain with
> 
> scv.tl.terminal_states(adata)
> scv.pl.scatter(adata, c=['root_cells', 'end_points’])

Attached

Olivier

**Comment by VolkerBergen** [comment]
Yes, here has been a bug in latent time sneaked in at v0.2, which is why shortly after we released v0.2.1. Please try on the latest version.

**Comment by ogandril** [comment]
OK, so here is the image with the  v0.2.1 version.
Latent time is in a different place but still not at the « source » of the fluxes…

Furthermore now the plotting of terminal states generates an error:

>>> scv.tl.terminal_states(adata)
computing terminal states
WARNING: Uncertain or fuzzy root cell identification. Please verify.
    identified 4 regions of root cells and 1 region of end points 
    finished (0:00:00) --> added
    'root_cells', root cells of Markov diffusion process (adata.obs)
    'end_points', end points of Markov diffusion process (adata.obs)
>>> scv.pl.scatter(adata, c=['root_cells', 'end_points’])
  File "<stdin>", line 1
    scv.pl.scatter(adata, c=['root_cells', 'end_points’])

**Comment by VolkerBergen** [comment]
I haven't received any img - could please send those again directly via github (instead of email)? The warning (fuzzy root cell identification) indicates that it is hard for the model to pick a clear unambiguous progenitor state.

**Comment by ogandril** [comment]
![Figure_5](https://user-images.githubusercontent.com/18306816/83859770-ae19b800-a71e-11ea-97e0-001cf567dd47.png)
Can you read the image now?

**Comment by VolkerBergen** [comment]
I would be mostly interested in `scv.pl.scatter(adata, c=['root_cells', 'end_points’])` as the root cell identification seems to be the culprit. You could also try setting the root cell manually via `scv.tl.latent_time(adata, root_key=index_of_root_cell)`.

**Comment by ogandril** [comment]
That was the point I raised in my previous message. This command now generates an error...

>>> scv.pl.scatter(adata, c=['root_cells', 'end_points’])
  File "<stdin>", line 1
    scv.pl.scatter(adata, c=['root_cells', 'end_points’])
                                                         ^
SyntaxError: EOL while scanning string literal

**Comment by ogandril** [comment]
Maybe because "it is hard for the model to pick a clear unambiguous progenitor state."?

**Comment by VolkerBergen** [comment]
I think one of the quotation marks was in a wrong format. Should be:
`scv.pl.scatter(adata, c=['root_cells', 'end_points'])`

**Comment by ogandril** [comment]
Oops. Indeed. Here comes the image.
![Figure_1](https://user-images.githubusercontent.com/18306816/83863116-30a47680-a723-11ea-9fa9-18119a547c73.png)

**Comment by VolkerBergen** [comment]
As expected, the root cells could not be identified correctly - and latent time is dependent on these. I'm a bit surprised that it looks so distorted, but we are aware that identifying root cells is indeed rather challenging and @Marius1311 has started implementing a conceptually much more sound and improved way of identifying these, deposited at https://github.com/theislab/cellrank. 

I would highly recommend you trying out cellrank - see whether root cells are correctly identified - install with `pip install git+https://github.com/theislab/cellrank` and run 
```
import cellrank as cr
scv.tl.velocity_graph(adata, mode_neighbors='connectivities') 
cr.tl.find_root(adata)
cr.tl.find_final(adata)
scv.tl.latent_time(adata, root_key='root_states_probs')
scv.pl.scatter(adata, ['root_states_probs', 'final_states_probs', 'latent_time']
```

Otherwise, it has to be set manually with indexing.

**Comment by ogandril** [comment]
I tried that.
Got two warnings and a final error:

>>> cr.tl.find_root(adata)
WARNING: Unable to load variances from `adata.uns['velocity_graph_uncertainties']`
>>> cr.tl.find_final(adata)
WARNING: Unable to load variances from `adata.uns['velocity_graph_uncertainties']`
>>> scv.tl.latent_time(adata, root_key='root_states_probs')
computing latent time using root_states_probs as prior
    finished (0:00:00) --> added 
    'latent_time', shared time (adata.obs)
>>> scv.pl.scatter(adata, ['root_states_probs', 'final_states_probs', 'latent_time'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.7/site-packages/scvelo/plotting/scatter.py", line 112, in scatter
    ax.append(scatter(adata, ax=pl.subplot(gs), **multi_kwargs, **scatter_kwargs, **kwargs))
  File "/opt/miniconda3/lib/python3.7/site-packages/scvelo/plotting/scatter.py", line 221, in scatter
    X_emb = adata.obsm['X_' + basis][:, get_components(components, basis)]
  File "/opt/miniconda3/lib/python3.7/site-packages/anndata/_core/aligned_mapping.py", line 148, in __getitem__
    return self._data[key]
KeyError: 'X_root_states_probs'

**Comment by VolkerBergen** [comment]
Warning can be ignored. Should have been `scv.pl.scatter(adata, c=['root_states_probs', 'final_states_probs', 'latent_time'])`.

**Comment by Marius1311** [comment]
Hi @ogandril, if any errors related to CellRank pop up, fee free to open an issue directly in the CelRank repo [here](https://github.com/theislab/cellrank)

**Comment by WeilerP** [comment]
Closing this as it seems a CellRank related issue.
