### ISSUE TITLE
using velocity_embedding_grid on a subset of adata

### ISSUE THREAD

**Issue by JonasMir** [theislab/scvelo#38]
Hi guys,
I am interested in calling the function velocity_embedding_grid not on the full adata object but only on a subset of it (e.g. on batch j). I would be happy with having a plot of the subset data in the old grid, i.e. the grid interpolation computed on the full data set. But actually it would even be better, to have a new interpolation grid based on the subset data only.
Thanks for any comments on this!
Best, Jonas

**Comment by VolkerBergen** [comment]
Thanks for pointing that out! Should work now as expected. Let me know if I missed anything.

**Comment by JonasMir** [comment]
Thanks for your quick response! With the new version I actually still get a mistake saying 
"IndexError: tuple index out of range".  
I address my subset data for example as "adata[(adata.obs['batch']=='day8'),:]".
Maybe I am missing something more basic here...

**Comment by VolkerBergen** [comment]
Ah pardon, should have given more details.

You can just call `scv.pl.velocity_embedding_grid(adata, groups='day8', color='batch']`.

However, the subsetting you just tried should actually work. You could check whether it finds anything called 'day8' with `(adata.obs['batch']=='day8').sum()`. Then subsetting `adata[adata.obs['batch']=='day8']` should not raise an error.

**Comment by JonasMir** [comment]
Ok, both ways of indexing work now! The latter started working after having updated scanpy (for whatever reason). Thanks for your help, Volker!
